### ISSUE TITLE
add tooltips to reduction parameters

### ISSUE THREAD

**Issue by pkienzle** [reflectometry/reduction#17]
Each parameter has a separate description field.  These can be fed through rst2html and provided as a list of html tags for each field that pops up when the user is entering values for the field.

This will allow users to see the **deprecated** notice on the join tolerance parameter.

**Comment by bmaranville** [comment]
I can do this pretty quick, but right now the client is only getting a plain description string for each module parameter as part of the instrument definition.  If you want to ship another string "description_html" or if you just want to replace what's in "description" with an rst2html output that might work.
The standard tooltip doesn't have html formatting anyway (it's just the title attribute of the html tag being hovered) so maybe it's not necessary to change.
