### ISSUE TITLE
caching needs small overhaul

### ISSUE THREAD

**Issue by bmaranville** [reflectometry/reduction#4]
Can't cache offspecular data type using JSON, as was done for refl files.  Nested self-describing dicts with embedded datatype just won't work.  

The serialization of ospec data gives a binary string - need to be able to make bundles of that.

Maybe we go back to structured storage (rpush and lrange?)

**Comment by pkienzle** [comment]
The use of JSON vs. some binary format seems to be orthogonal to the
rpush/lrange question.  Or do I misunderstand the question?

**Comment by bmaranville** [comment]
Not orthogonal... Bundles seem to work because lists pop right into/out 
of JSON structures.  If you are going to store data in a binary string, 
and can't use JSON anymore, the trick of throwing the whole structure 
into the serialization doesn't work (goes all the way up to the node 
level right now: {"terminal_id1": {"datatype": "refldata", "values": 
[<serialized item>, <serialized item>,...]}, "terminal_id2": ...})
Caching the list at the bottom of that chain becomes the problem if each 
data object is a binary string, which is why it's connected to the 
lrange/rpush question.

**Comment by bmaranville** [comment]
I found a library called ujson that allows non-ascii (binary!) strings in JSON encodings.  Also looking into BSON as a dropin replacement for JSON for this.

**Comment by pkienzle** [comment]
Changed to pickle for redis store.
